{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "beyla.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  name: {{ template "beyla.fullname" .  }}
spec:
  endpoints:
  - path: /metrics
    port: {{ .Values.service.portName }}
  - path: /internal/metrics
    port: {{ .Values.service.portName }}
  {{- if .Values.serviceMonitor.interval }}
  interval: {{ .Values.serviceMonitor.interval }}
  {{- end }}
  {{- if .Values.serviceMonitor.metricRelabelings }}
  metricRelabelings:
  {{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 6) . }}
  {{- end }}
  {{- if .Values.serviceMonitor.relabelings }}
  relabelings:
  {{ tpl (toYaml .Values.serviceMonitor.relabelings | nindent 6) . }}
  {{- end }}
  {{- with .Values.serviceMonitor.tlsConfig }}
  tlsConfig:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "beyla.selectorLabels" . | nindent 6 }}
{{- end }}
