# Build the testserver binary
# Docker command must be invoked from the projec root directory
FROM fullstorydev/grpcurl:latest-alpine AS builder

WORKDIR /

# Copy the run script
COPY test/integration/components/go_grpc_server_mux/ping.sh .

ENTRYPOINT [ "/bin/sh", "/ping.sh" ]