---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  labels:
    app: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      volumes:
        - name: grafana-agent-config
          configMap:
            name: grafana-agent-config
      containers:
        - name: grafana-agent
          image: grafana/agent:main
          command:
            - "/usr/bin/agent"
            - "--config.file=/grafana-agent-config/agent-config.yml"
            - "-server.http.address=127.0.0.1:9090"
            - "-server.grpc.address=127.0.0.1:9091"
          ports:
            - containerPort: 4318
              protocol: TCP
              name: http-traces
          volumeMounts:
            - mountPath: /grafana-agent-config
              readOnly: true
              name: grafana-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
spec:
  selector:
    app: grafana-agent
  ports:
    - port: 4318
      protocol: TCP
      targetPort: http-traces
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-autoinstrumenter
  labels:
    app: http-autoinstrumenter
spec:
  selector:
    matchLabels:
      app: http-autoinstrumenter
  template:
    metadata:
      labels:
        app: http-autoinstrumenter
    spec:
      hostPID: true # require to access processes in the host
      containers:
        - name: http-autoinstrumenter
          image: mariomac/http-autoinstrument:latest
          #imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            privileged: true # TODO: change by individual capabilities
          command:
            - "/otelhttp"
          env:
            - name: EXECUTABLE_NAME
              value: "goblog"
            - name: OTEL_TRACES_ENDPOINT
              value: "grafana-agent:4318"
