# Feel free to replace the demo app by something different,
# but it needs to bring the autoinstrumenter as a sidecar container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goblog
  labels:
    app: goblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goblog
  template:
    metadata:
      labels:
        app: goblog
    spec:
      # required so the sidecar instrumenter can access the service process
      shareProcessNamespace: true
      containers:
        - name: goblog
          image: mariomac/goblog:dev
          imagePullPolicy: IfNotPresent
          command: [ "/goblog" ]
          env:
            - name: "GOBLOG_CONFIG"
              value: "/sample/config.yml"
          ports:
            - containerPort: 8443
              name: https
        - name: autoinstrumenter
          image: grafana/beyla:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            # uncomment the following line if the logs still show permission errors:
            # privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          env:
            - name: SERVICE_NAME
              value: "goblog"
            - name: PRINT_TRACES
              value: "true"
            - name: OPEN_PORT
              value: "8443"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-agent:4318"
            - name: LOG_LEVEL
              value: "DEBUG"
---
apiVersion: v1
kind: Service
metadata:
  name: goblog
spec:
  selector:
    app: goblog
  ports:
    - port: 8443
      protocol: TCP
      targetPort: https
