config:
  data:
    network:
      enable: true
    discovery:
      services:
        - k8s_namespace: demo
        - k8s_namespace: blog
    attributes:
      kubernetes:
        enable: true
    routes:
      unmatched: heuristic
env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
envValueFrom:
  OTEL_EXPORTER_OTLP_HEADERS:
      secretKeyRef:
        key: otlp-headers
        name: grafana-secret