codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false