issues:
  exclude-dirs:
    - configs
    - docs
    - .obi-src
  exclude-rules:
    # revive returns false indent-error-flow errors in some cases where
    # an "else" clause is required to access the if condition context
    - path: .*
      linters:
        - revive
      text: indent-error-flow

    # exclude deprecated API usage errors. If we deprecate some properties is because we don't want to remove them
    # (hide/undocument them, but keep supporting them until the next major version)
    - path: .*
      linters:
        - staticcheck
      text: "SA1019:"
run:
  go: "1.24"
  build-tags:
    - integration
linters:
  enable:
    - errcheck
    - errorlint
    - cyclop
    - errname
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
  disable:
    - exhaustive
linters-settings:
  gocritic:
    enabled-checks:
      - rangeExprCopy
      - rangeValCopy
      - indexAlloc
      - commentedOutCode
  cyclop:
    max-complexity: 12

