run:
  skip-dirs:
    - configs
    - docs
  build-tags:
    - integration
linters:
  enable:
    - errcheck
    - errorlint
    - cyclop
    - errname
    - exportloopref
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
#    - structcheck Disable until they properly support generics
    - stylecheck
    - typecheck
    - unused
  disable:
    - exhaustive
linters-settings:
  stylecheck:
    go: "1.21"
  gocritic:
    enabled-checks:
      - rangeExprCopy
      - rangeValCopy
      - indexAlloc
      - deprecatedComment
  cyclop:
    max-complexity: 12

