
image:
  repository: grafana/beyla
  # Overrides the Grafana image tag whose default is the chart appVersion
  tag: "main"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

