FROM node:18-slim@sha256:f9ab18e354e6855ae56ef2b290dd225c1e51a564f87584b9bd21dd651838830e

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY internal/test/integration/components/nodejsdist .

# Install NodeJS express
RUN npm init -y && npm install express axios

EXPOSE 5006

# Run the node app
CMD [ "node", "service-r.js" ]
