FROM php:8.5-fpm@sha256:d4871a19b9e56a00263921ebb1aea25ba57010e98c8861f33fef42e9ceb62614

SHELL ["/bin/bash", "-c"]

RUN chmod 1777 /tmp
RUN  apt-get update -y && apt-get install -y procps 
 
RUN groupadd -f www-data && \
    (id -u www-data &> /dev/null || useradd -G www-data www-data -D)
 
RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

RUN docker-php-ext-install \
            pdo_mysql \
            sockets 

EXPOSE 9000

RUN install -d -m 0755 -o www-data -g www-data /run/php-fpm

COPY --chown=www-data:www-data internal/test/integration/components/php/unix_sock_sql/src/ /var/www/html/
COPY internal/test/integration/components/php/unix_sock_sql/config/php/ /usr/local/etc/
COPY internal/test/integration/components/php/unix_sock_sql/config/php/php/php.ini  /usr/local/etc/php/

RUN install -d -m 0755 -o www-data -g www-data /var/lib/php/sessions

RUN install -o www-data -g www-data -d /var/log/php && \
    install -o www-data -g www-data /dev/null /var/log/php/error.log && \ 
    install -o www-data -g www-data /dev/null /var/log/php/php-fpm.log && \
    chown -R www-data:www-data /var/www

WORKDIR /var/www/html    

USER www-data
