FROM mcr.microsoft.com/dotnet/sdk:latest

# Set the working directory to /build
WORKDIR /build

# Copy the source code into the image for building
COPY test/ test/

WORKDIR /build/test/integration/components/dotnetserver

RUN dotnet dev-certs https

EXPOSE 7033

# Run the .net app
CMD [ "dotnet", "run", "--launch-profile", "https"]
