# Dockerfile that will build a container that runs python with FastAPI and uvicorn on port 8080
FROM python:3.12@sha256:b499cef422563a0ea06776df379781343de803291ffcfcd5513faf87a36ede6b
EXPOSE 8080
RUN apt update
RUN pip install fastapi uvicorn mysql-connector-python
COPY main_mysql.py /main.py
CMD ["uvicorn", "--port", "8080", "--host", "0.0.0.0", "main:app"]