---
apiVersion: v1
kind: Service
metadata:
  name: testserver
spec:
  selector:
    app: testserver
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  labels:
    app: testserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      name: testserver
      labels:
        app: testserver
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: testclient
spec:
  containers:
    - name: testclient
      image: fedora
      command:
        - sh
        - -c
        - 'while true; do curl -v http://testserver:8080 ; sleep 1; done'
