version: "3.8"

services:
  nginx:
    image: nginx:latest@sha256:7f0adca1fc6c29c8dc49a2e90037a10ba20dc266baaed0988e9fb4d0d8b85ba0
    container_name: demo-nginx
    ports:
      - 3333:3330
    volumes:
      - ./configs/:/etc/nginx
    depends_on:
      gotestserver:
        condition: service_started
      javatestserver:
        condition: service_started
      rusttestserver:
        condition: service_started

  # Beyla for NGINX
  nginxbeyla:
    image: grafana/beyla:latest@sha256:f0160f97603e560fdc75aa2b6b2b91f6823ac5d9aadc23b9b4d7770bfeb9bd83
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-nginxbeyla
    privileged: true
    network_mode: "service:nginx"
    pid: "service:nginx"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_TRACE_PRINTER: "text"
      BEYLA_OPEN_PORT: "3330"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-nginx"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4018"
    depends_on:
      nginx:
        condition: service_started

  # Go test server
  # Test server source can be found at internal/test/integration/components/testserver
  gotestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-go/0.0.1@sha256:01da627c6f52e6f18440660a7f4c73af9c1f84667f6b8f3ff1826ea3cf0610a9
    container_name: demo-gotestserver
    #ports:
    #  - "8084:8080"

  # Beyla for Java Spring Boot 3.0 GraalVM Native Image
  gobeyla:
    image: grafana/beyla:latest@sha256:f0160f97603e560fdc75aa2b6b2b91f6823ac5d9aadc23b9b4d7770bfeb9bd83
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-gobeyla
    privileged: true
    network_mode: "service:gotestserver"
    pid: "service:gotestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_TRACE_PRINTER: "text"
      BEYLA_OPEN_PORT: "8080"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-go-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4018"
    depends_on:
      gotestserver:
        condition: service_started

  # Java Spring Boot 3.0 GraalVM Native Image test server
  # Test server source can be found at internal/test/integration/components/javatestserver
  javatestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-graalvm-native/0.0.1@sha256:52d1fb320b5d644e0742cf9295b29cbbbf264c39b7ee74087147009bad9a3546
    container_name: demo-javatestserver
    #ports:
    #  - "8085:8085"

  # Beyla for Java Spring Boot 3.0 GraalVM Native Image
  javabeyla:
    image: grafana/beyla:latest@sha256:f0160f97603e560fdc75aa2b6b2b91f6823ac5d9aadc23b9b4d7770bfeb9bd83
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-javabeyla
    privileged: true
    network_mode: "service:javatestserver"
    pid: "service:javatestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_TRACE_PRINTER: "text"
      BEYLA_OPEN_PORT: "8085"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-graalvm-native-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4018"
    depends_on:
      javatestserver:
        condition: service_started

  # Rust Actix test server
  # Test server source can be found at internal/test/integration/components/rusttestserver
  rusttestserver:
    image: ghcr.io/grafana/beyla-demo/greeting-actix-rust/0.0.1@sha256:92d58004021fc9ade85670221b8c55f26535c4cb496891a6520526234eabb990
    container_name: demo-rusttestserver
    #ports:
    #  - "8086:8090"

  # Beyla for Rust Actix
  rustbeyla:
    image: grafana/beyla:latest@sha256:f0160f97603e560fdc75aa2b6b2b91f6823ac5d9aadc23b9b4d7770bfeb9bd83
    volumes:
      - ./configs/:/configs
      - ./system/sys/kernel/security:/sys/kernel/security
    container_name: demo-rustbeyla
    privileged: true
    network_mode: "service:rusttestserver"
    pid: "service:rusttestserver"
    environment:
      BEYLA_CONFIG_PATH: "/configs/beyla-config.yml"
      BEYLA_TRACE_PRINTER: "text"
      BEYLA_OPEN_PORT: "8090"
      BEYLA_SERVICE_NAMESPACE: "demo"
      OTEL_SERVICE_NAME: "demo-rust-service"
      BEYLA_LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4018"
    depends_on:
      rusttestserver:
        condition: service_started

  # Grafana Agent
  agent:
    image: grafana/agent@sha256:473928c1cace5a23fdb1c187dba4ec0fe733d4627ae65383861a7beb997db88c
    container_name: demo-agent
    command:
      - run
      - /etc/agent/agent-config.river
    volumes:
      - ./configs/:/etc/agent
    environment:
      AGENT_MODE: "flow"
    ports:
      - "4017:4017"
      - "4018:4018"

  # Tempo
  tempo:
    image: grafana/tempo@sha256:d214f1de6974186ff5ddb420637f87f2436f25a9d4a33fb72d16a8e38b9362fb
    container_name: demo-tempo
    command:
      - -config.file
      - /etc/tempo/tempo-config.yaml
    volumes:
      - ./configs/:/etc/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  # Mimir -config.file=config-mimir.yaml -server.grpc-listen-port=9096
  mimir:
    image: grafana/mimir@sha256:73a05141c43fe2e7c4231359ab48122f538a0abe51f454df1b56678c4948cbf0
    container_name: demo-mimir
    command:
      - -config.file=/etc/mimir/mimir-config.yaml
      - -server.grpc-listen-port=9096
    volumes:
      - ./configs/:/etc/mimir
    ports:
      - "9009:9009"
      - "9096:9096"

  grafana:
    image: grafana/grafana@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    container_name: demo-grafana
    volumes:
      - ./configs/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
