{
 "title": "eBPF RED Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "Service", "label": "Service", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Slowest HTTP routes (P95)",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(http_route, job) (5,  max by (http_route, job) (histogram_quantile(0.95,  (sum by(http_route, job, le) (rate(http_server_duration_bucket[$__rate_interval])))))))",
     "legendFormat": "{{job}} - {{http_route}}"
    }
   ]
  },
  {
   "title": "Slowest RPC methods (P95)",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(rpc_method, job) (5,  max by (rpc_method, job) (histogram_quantile(0.95,  (sum by(rpc_method, job, le) (rate(rpc_server_duration_bucket[$__rate_interval])))))))",
     "legendFormat": "{{job}} - {{http_route}}"
    }
   ]
  },
  { "title": "Inbound: $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "Service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(http_server_duration_bucket{job=\"$Service\"}[$__rate_interval])))",
     "legendFormat": "HTTP p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{job=\"$Service\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "sum(rate(http_server_duration_sum{job=\"$Service\"} [$__rate_interval])) / sum(rate(http_server_duration_count{job=\"$Service\"} [$__rate_interval]))",
     "legendFormat": "HTTP Avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(rpc_server_duration_bucket{job=\"$Service\"}[$__rate_interval])))",
     "legendFormat": "RPC p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(job, le) (rate(rpc_server_duration_bucket{job=\"$Service\"}[$__rate_interval])))",
     "legendFormat": "RPC p95"
    },
    {
     "expr": "sum(rate(rpc_server_duration_sum{job=\"$Service\"} [$__rate_interval])) / sum(rate(rpc_server_duration_count{job=\"$Service\"} [$__rate_interval]))",
     "legendFormat": "RPC Avg"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"$Service\"} [$__rate_interval])) by (http_status_code)",
     "legendFormat": "HTTP server - {{http_status_code}}"
    },
    {
     "expr": "sum(rate(rpc_server_duration_count{job=\"$Service\"} [$__rate_interval])) by (job, rpc_grpc_status_code)",
     "legendFormat": "RPC server (status {{rpc_grpc_status_code}})"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(http_server_duration_count{job=\"$Service\",http_status_code=~\"(4|5).*\"}[$__rate_interval])) / ignoring(http_status_code) group_left sum(rate(http_server_duration_count{job=\"$Service\"}[$__rate_interval]))",
     "legendFormat": "HTTP server - {{http_status_code}}"
    },
    {
     "expr": "sum by (rpc_grpc_status_code) (rate(rpc_server_duration_count{job=\"$Service\",rpc_grpc_status_code!=\"0\"}[$__rate_interval])) / ignoring(rpc_grpc_status_code) group_left sum(rate(rpc_server_duration_count{job=\"$Service\"}[$__rate_interval]))",
     "legendFormat": "RPC server (status {{rpc_grpc_status_code}})"
    }
   ]
  },
  { "title": "Outbound: $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }, "repeat": "Service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(http_client_duration_bucket{job=\"$Service\"}[$__rate_interval])))",
     "legendFormat": "HTTP p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_bucket{job=\"$Service\"}[$__rate_interval])) by (job, le)) ",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "sum(rate(http_client_duration_sum{job=\"$Service\"} [$__rate_interval])) / sum(rate(http_client_duration_count{job=\"$Service\"} [$__rate_interval]))",
     "legendFormat": "HTTP Avg"
    },
    {
     "expr": "sum(rate(rpc_client_duration_sum{job=\"$Service\"} [$__rate_interval])) / sum(rate(rpc_client_duration_count{job=\"$Service\"} [$__rate_interval]))",
     "legendFormat": "RPC Avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(rpc_client_duration_bucket{job=\"$Service\"}[$__rate_interval])))",
     "legendFormat": "RPC p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rpc_client_duration_bucket{job=\"$Service\"}[$__rate_interval])) by (job, le)) ",
     "legendFormat": "RPC p95"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_duration_count{job=\"$Service\"} [$__rate_interval])) by (job, http_status_code)",
     "legendFormat": "HTTP client - {{http_status_code}}"
    },
    {
     "expr": "sum(rate(rpc_client_duration_count{job=\"$Service\"} [$__rate_interval])) by (job, rpc_grpc_status_code)",
     "legendFormat": "RPC client (status {{rpc_grpc_status_code}})"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(http_client_duration_count{job=\"$Service\",http_status_code=~\"5.*\"}[$__rate_interval])) / ignoring(http_status_code) group_left sum(rate(http_client_duration_count{job=\"$Service\"}[$__rate_interval]))",
     "legendFormat": "HTTP client - {{http_status_code}}"
    },
    {
     "expr": "sum by (rpc_grpc_status_code) (rate(rpc_client_duration_count{job=\"$Service\",rpc_grpc_status_code!=\"0\"}[$__rate_interval])) / ignoring(rpc_grpc_status_code) group_left sum(rate(rpc_client_duration_count{job=\"$Service\"}[$__rate_interval]))",
     "legendFormat": "RPC client (status {{rpc_grpc_status_code}})"
    }
   ]
  }
 ]
}