# Build the testserver binary
# Docker command must be invoked from the project root directory
FROM fullstorydev/grpcurl:latest-alpine@sha256:4614424ed58e9b9837c48b6b8eadb9ef40491d5af3499bcc8b378e9c64a9e4a9 AS builder

WORKDIR /

# Copy the run script
COPY internal/test/integration/components/go_grpc_server_mux/ping_tls.sh .

ENTRYPOINT [ "/bin/sh", "/ping_tls.sh" ]