{{- if (not .Values.externalBeylaConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beyla.fullname" . }}
  namespace: {{ include "beyla.namespace" . }}
  labels:
    {{- include "beyla.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  beyla-config.yml: |
  {{- toYaml .Values.configmapData | nindent 4}}
{{- end }}
