{{ $internalMetricsPort := include "beyla.internalMetricsPort" . }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "beyla.fullname" . }}
  namespace: {{ include "beyla.namespace" .}}
  labels:
    {{- include "beyla.labels" . | nindent 2 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
{{ include "beyla.selectorLabels" . | indent 6 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
{{ include "beyla.selectorLabels" . | indent 8 }}
    spec:
     {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "beyla.serviceAccountName" . }}
     {{- end }}
      hostPID: true  #important!
      volumes:
        - name: beyla-config
          configMap:
            name: {{ default (include "beyla.fullname" .) .Values.externalBeylaConfigMap}}
      containers:
        - name: beyla
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          ports:
          {{- if ne $internalMetricsPort "0" }}
          - containerPort: {{ $internalMetricsPort }}
            protocol: TCP
          {{- end }}
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
            - name: BEYLA_PRINT_TRACES
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production"
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          {{- range $key, $value := .Values.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
          {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- with .Values.nodeSelector }}          
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
