apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "beyla.fullname" . }}
  namespace: {{ include "beyla.namespace" .}}
  labels:
    {{- include "beyla.labels" . | nindent 2 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      instrumentation: {{ include "beyla.fullname" . }}
  template:
    metadata:
      labels:
        instrumentation: {{ include "beyla.fullname" . }}
    spec:
     {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "beyla.serviceAccountName" . }}
     {{- end }}
      hostPID: true  #important!
      volumes:
        - name: beyla-config
          configMap:
            {{- if .Values.useExistingConfigMap }}
            name: {{ .Values.useExistingConfigMap }}
            {{- else }}
            name: {{ include "beyla.fullname" . }}
            {{- end }}
      containers:
        - name: beyla
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: beyla-config
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
            - name: BEYLA_PRINT_TRACES
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production"
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          {{- range $key, $value := .Values.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 10 }}
          {{- end }}