FROM ruby:3.0.2

# Set the working directory to /build
WORKDIR /build

# Copy the source code into the image for building
COPY test/ test/

WORKDIR /build/test/integration/components/rubytestserver/testapi

# Install NodeJS express
RUN gem install rails
RUN gem install bundler rails
RUN bundle install

EXPOSE 3043

# Run the node app
CMD [ "rails", "server", "-b", "ssl://0.0.0.0:3043?key=config/key.pem&cert=config/cert.pem" ]
