FROM eclipse-temurin:17@sha256:5a66a3ffd8728ed6c76eb4ec674c37991ac679927381f71774f5aa44cf420082 AS javabuilder

# Install tar and gzip to extract the Maven binaries
RUN apt install -y tar gzip

# Install Maven
ARG USER_HOME_DIR="/cache"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY internal/test/integration/components/javakafka/.mvn .mvn/
COPY internal/test/integration/components/javakafka/mvnw mvnw
COPY internal/test/integration/components/javatestserver/src src/
COPY internal/test/integration/components/javatestserver/pom.xml pom.xml

RUN java -version
RUN ./mvnw -version

# Build
RUN ./mvnw clean package

# The App Image
FROM eclipse-temurin:17.0.17_10-jre@sha256:75ab7d1b4b18483e9245342cbee253b558952c1def5c1c18956196330a01683e

EXPOSE 8085

# Copy the native executable into the containers
COPY --from=javabuilder /build/target/greeting-service-1.2.0.jar .
CMD [ "java", "-jar", "/greeting-service-1.2.0.jar" ]