package tpencode

// Corpus is a mixed k8s / traditional-ops set of (namespace, name) pairs.
// Non-k8s names are what Beyla would infer from comm / systemd / OTEL_SERVICE_NAME
// on EC2 or ansible-managed VMs.
var Corpus = []Identity{
	{Name: "nginx"},
	{Name: "httpd"},
	{Name: "sshd"},
	{Name: "postgres"},
	{Name: "redis"},
	{Name: "mysqld"},
	{Name: "myapp"},
	{Name: "app"},
	{Name: "web01"},
	{Name: "beyla"},
	{Name: "grafana"},
	{Name: "prometheus"},
	{Name: "a"},
	{Namespace: "prod", Name: "api"},
	{Namespace: "prod", Name: "web"},
	{Namespace: "prod", Name: "worker"},
	{Namespace: "prod", Name: "nginx"},
	{Namespace: "staging", Name: "api"},
	{Namespace: "dev", Name: "app"},
	{Namespace: "ops", Name: "node-exporter"},
	{Namespace: "eu-west-1", Name: "checkout"},
	{Namespace: "default", Name: "checkout"},
	{Namespace: "default", Name: "frontend"},
	{Namespace: "default", Name: "cartservice"},
	{Namespace: "default", Name: "nginx"},
	{Namespace: "production", Name: "checkout"},
	{Namespace: "production", Name: "payments-api"},
	{Namespace: "production", Name: "recommendation"},
	{Namespace: "production", Name: "checkout-service"},
	{Namespace: "production", Name: "payments-gateway"},
	{Namespace: "kube-system", Name: "coredns"},
	{Namespace: "observability", Name: "beyla"},
	{Namespace: "monitoring", Name: "prometheus"},
	{Namespace: "a", Name: "b"},
	{Name: "ip-10-0-1-23"},
	{Namespace: "customer-prod", Name: "order-processing-worker"},
	{Namespace: "production", Name: "very-long-deployment-name-that-will-not-fit"},
}
