---
kind: pipeline
name: ebpf-autoinstrument
steps:
- image: thegeeklab/drone-docker-buildx:24
  name: ebpf-autoinstrument-dryrun-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/ebpf-autoinstrument-dryrun
    tags: test
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request
- image: thegeeklab/drone-docker-buildx:24
  name: ebpf-autoinstrument-tagged-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/ebpf-autoinstrument
    tags: latest
    username:
      from_secret: docker_username
  when:
    event:
    - tag
- image: thegeeklab/drone-docker-buildx:24
  name: ebpf-autoinstrument-main-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/ebpf-autoinstrument
    tags: main
    username:
      from_secret: docker_username
  when:
    event:
    - push
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: signature
hmac: c8e7bb5d13a900799135d67a42a57f199678aa6593a1a4371a449313f5e298b7

...
