---
kind: pipeline
name: beyla
steps:
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-dryrun-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    build_args_from_env:
    - DRONE_TAG
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla-dryrun
    tags: test
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-tagged-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    build_args_from_env:
    - DRONE_TAG
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: ""
    username:
      from_secret: docker_username
  when:
    event:
    - tag
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-latest-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    build_args_from_env:
    - DRONE_TAG
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: latest
    username:
      from_secret: docker_username
  when:
    event:
    - tag
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-main-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    build_args_from_env:
    - DRONE_TAG
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: main
    username:
      from_secret: docker_username
  when:
    event:
    - push
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: signature
hmac: 80d28c3b23c53bdd6b5c90e2881d39901c0b01d4cdcc435de61d34112a267965

...
