---
kind: pipeline
name: beyla
steps:
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-dryrun-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla-dryrun
    tags: test
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-tagged-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: ""
    username:
      from_secret: docker_username
  when:
    event:
    - tag
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-latest-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: latest
    username:
      from_secret: docker_username
  when:
    event:
    - tag
- image: thegeeklab/drone-docker-buildx:24
  name: beyla-main-docker-buildx
  privileged: true
  settings:
    auto_tag: false
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/beyla
    tags: main
    username:
      from_secret: docker_username
  when:
    event:
    - push
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: signature
hmac: b2d0a0ed30050f8632ab6331f58a4d147c8e155e5f28a51de72a1d3b3a46759e

...
