# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.25.6@sha256:c1252002e1a0ba34875937d59d4f123d0a4673a50f69c38fca4175cae194c7f9 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/integration/components/beyla/beyla_wrapper.sh /beyla_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY vendor/ vendor/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

# Build
RUN make compile-for-coverage

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/beyla /beyla
COPY --from=builder /beyla_wrapper.sh /beyla_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/beyla_wrapper.sh" ]