# Dockerfile that will build a container that runs python flask with gunicorn on port 8380
FROM python:3.11.6-slim
EXPOSE 8380
RUN pip install flask gunicorn requests
# Alternative: RUN pip install flask uwsgi

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY test/integration/components/pythonserver .

CMD ["gunicorn", "--keyfile", "server.key", "--certfile", "server.crt", "-w", "4", "-b", "0.0.0.0:8380", "main:app"]
