# Build the testserver binary
# Docker command must be invoked from the project root directory
FROM golang:1.25@sha256:6bac879c5b77e0fc9c556a5ed8920e89dab1709bd510a854903509c828f67f96 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /src

# Copy the go manifests and source
COPY vendor/ vendor/
COPY test/ test/
COPY go.mod go.mod
COPY go.sum go.sum

# Build
RUN go build -o testserver ./test/integration/components/testserver/testserver.go

# Create final image from minimal + built binary
FROM debian:bookworm-slim@sha256:78d2f66e0fec9e5a39fb2c72ea5e052b548df75602b5215ed01a17171529f706

WORKDIR /
RUN mkdir -p x509
COPY --from=builder /src/test/integration/components/testserver/x509/server_test_cert.pem x509
COPY --from=builder /src/test/integration/components/testserver/x509/server_test_key.pem x509
COPY --from=builder /src/test/integration/components/testserver/duplicate_testserver.sh .
COPY --from=builder /src/testserver duped_service
USER 0:0

CMD [ "sh", "/duplicate_testserver.sh" ]