# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.26.1@sha256:c42e4d75186af6a44eb4159dcfac758ef1c05a7011a0052fe8a8df016d8e8fb9 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/beyla_extensions/components/beyla/beyla_wrapper.sh /beyla_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY vendor/ vendor/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

# Build
RUN make compile-for-coverage

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/beyla /beyla
COPY --from=builder /beyla_wrapper.sh /beyla_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/beyla_wrapper.sh" ]
