// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64
// +build arm64

package watcher

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfHttpConnectionMetadataT struct {
	Pid struct {
		HostPid   uint32
		UserPid   uint32
		Namespace uint32
	}
	Type uint8
}

type bpfPidConnectionInfoT struct {
	Conn struct {
		S_addr [16]uint8
		D_addr [16]uint8
		S_port uint16
		D_port uint16
	}
	Pid uint32
}

type bpfPidKeyT struct {
	Pid       uint32
	Namespace uint32
}

type bpfWatchInfoT struct {
	Flags   uint64
	Payload uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeSecuritySocketBind *ebpf.ProgramSpec `ebpf:"kprobe_security_socket_bind"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FilteredConnections *ebpf.MapSpec `ebpf:"filtered_connections"`
	PidCache            *ebpf.MapSpec `ebpf:"pid_cache"`
	ValidPids           *ebpf.MapSpec `ebpf:"valid_pids"`
	WatchEvents         *ebpf.MapSpec `ebpf:"watch_events"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FilteredConnections *ebpf.Map `ebpf:"filtered_connections"`
	PidCache            *ebpf.Map `ebpf:"pid_cache"`
	ValidPids           *ebpf.Map `ebpf:"valid_pids"`
	WatchEvents         *ebpf.Map `ebpf:"watch_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FilteredConnections,
		m.PidCache,
		m.ValidPids,
		m.WatchEvents,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeSecuritySocketBind *ebpf.Program `ebpf:"kprobe_security_socket_bind"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeSecuritySocketBind,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_arm64.o
var _BpfBytes []byte
