name: Build and Commit eBPF Binaries

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build-ebpf:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow commits back to the repo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Compile eBPF Programs
        run: |
          make docker-generate

      # NOTE: The user email is {user.id}+{user.login}@users.noreply.github.com.
      # See users API: https://api.github.com/users/github-actions%5Bbot%5D
      - name: Commit Compiled eBPF Programs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "CI: Auto-build eBPF binaries [skip ci]" || exit 0
          git push

