name: Clang Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Set restrictive permissions at workflow level
permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-latest
    # Only run if security check passed
    needs: security-check
    if: ${{ needs.security-check.outputs.security_cleared == 'true' || !failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Clang-Format
        run: sudo apt-get install clang-format-19

      - name: Check Clang Format
        run: |
          # Check for modified C/C++ files
          files=$(git diff --name-status origin/main...HEAD | awk '$1 != "D" && /\.(c|cpp|h)$/ { print ($3 != "" ? $3 : $2) }' | (grep -v '^vendor' || true))
          if [ -z "$files" ]; then
            echo "No C/C++ files modified."
            exit 0
          fi

          # Run clang-format and check for changes
          clang-format-19 -i $files
          if ! git diff --exit-code $files; then
            echo "Error: Some files are not formatted correctly. Please run clang-format on the modified files or use the provided pre-commit hook."
            exit 1
          fi

  # Reference the security-check workflow
  security-check:
    uses: ./.github/workflows/security-check.yml
    secrets: inherit

