name: Release Helm chart
on:
  workflow_dispatch:

jobs:
  release-beyla-helm-chart:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@77e5ea2de369fa1ff3441b08765c164be209eaa2
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    with:
      charts_dir: charts/beyla
      cr_configfile: .github/configs/cr.yml
      ct_configfile: .github/configs/ct.yml
      github_app: mimir-helm-release
