name: Release Helm chart
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-beyla-helm-chart:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@94d62a9bd8829f8d32da6f721905b8f59e3e94b8
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    with:
      github_app: grafana-beyla-bot
      charts_dir: charts/beyla
      cr_configfile: .github/configs/cr.yml
      ct_configfile: .github/configs/ct.yml
