name: Port to Upstream OTel eBPF Instrumentation

on:
  pull_request:
    types: [opened, synchronize, labeled, closed]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  port-to-upstream:
    if: |
      github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            UPSTREAM_GITHUB_TOKEN=github-app:upstream-github-token
      - name: Checkout Beyla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push changes to fork for upstream PR
        env:
          GH_TOKEN: ${{ env.UPSTREAM_GITHUB_TOKEN }}
        run: |
          BRANCH=port/${{ github.event.pull_request.number }}-to-upstream
          git checkout -b $BRANCH
          git remote add upstream-fork https://x-access-token:${GH_TOKEN}@github.com/grafana/opentelemetry-ebpf-instrumentation.git
          git push upstream-fork $BRANCH --force
      - name: Create PR to upstream repo
        env:
          GH_TOKEN: ${{ env.UPSTREAM_GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "[port] #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" \
            --body "Automated port of #${{ github.event.pull_request.number }} from grafana/beyla." \
            --repo open-telemetry/opentelemetry-ebpf-instrumentation \
            --head grafana:port/${{ github.event.pull_request.number }}-to-upstream \
            --base main \
            --draft
