name: Port PRs to Upstream OTel eBPF Instrumentation

# Simple trigger to run on every push or PR action
on: [push, pull_request]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  port-to-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event path: ${{ github.event_path }}"
          echo "Ref: ${{ github.ref }}"
          
      - name: Get secrets from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            GITHUB_APP_ID=github-app:app-id
            GITHUB_APP_INSTALLATION_ID=github-app:app-installation-id
            GITHUB_APP_PRIVATE_KEY=github-app:private-key
            
      - name: Checkout Beyla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_APP_PRIVATE_KEY }}
          installation-id: ${{ env.GITHUB_APP_INSTALLATION_ID }}
          owner: grafana
          repositories: "opentelemetry-ebpf-instrumentation"
          permission-contents: write
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: grafana/opentelemetry-ebpf-instrumentation
          token: ${{ steps.app-token.outputs.token }}
          path: opentelemetry-ebpf-instrumentation
          
      - name: Process labeled PRs
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Running PR processing..."
          
          # Find labeled PRs - use explicit output format to avoid parsing issues
          LABELED_PRS=$(gh pr list --repo grafana/beyla --label "port-to-otel-ebpf-inst" --json number,title,url,baseRefName,state)
          echo "Found labeled PRs JSON:"
          echo "$LABELED_PRS" | jq '.'
          
          # Count the PRs found
          PR_COUNT=$(echo "$LABELED_PRS" | jq length)
          echo "Number of PRs to process: $PR_COUNT"
          
          # Process each labeled PR (with explicit iteration)
          for i in $(seq 0 $((PR_COUNT-1))); do
            PR_JSON=$(echo "$LABELED_PRS" | jq ".[$i]")
            PR_NUM=$(echo "$PR_JSON" | jq -r '.number')
            PR_TITLE=$(echo "$PR_JSON" | jq -r '.title')
            PR_URL=$(echo "$PR_JSON" | jq -r '.url')
            PR_BASE_BRANCH=$(echo "$PR_JSON" | jq -r '.baseRefName')
            PR_STATE=$(echo "$PR_JSON" | jq -r '.state')
            
            echo "================================================================"
            echo "Processing PR #${PR_NUM}: ${PR_TITLE} (${PR_STATE})"
            echo "================================================================"
            
            # Skip closed PRs
            if [ "$PR_STATE" == "CLOSED" ]; then
              echo "PR is closed. Skipping."
              continue
            fi
            
            # Try fetching the PR branch
            echo "Fetching PR branch..."
            if ! git fetch origin pull/${PR_NUM}/head:pr-${PR_NUM} 2>/dev/null; then
              echo "Failed to fetch PR #${PR_NUM}. Continuing with next PR."
              continue
            fi
            
            # Checkout the PR branch
            git checkout pr-${PR_NUM}
            
            # Get base/head SHAs
            BASE_SHA=$(git merge-base origin/${PR_BASE_BRANCH} pr-${PR_NUM} 2>/dev/null || git merge-base origin/main pr-${PR_NUM})
            HEAD_SHA=$(git rev-parse HEAD)
            
            echo "Base SHA: $BASE_SHA"
            echo "Head SHA: $HEAD_SHA"
            
            # Get changed files (excluding vendor/licenses and workflows)
            CHANGED_FILES=$(git diff --name-only ${BASE_SHA} ${HEAD_SHA} | grep -v "vendor/" | grep -v "LICENSE" | grep -v "third_party_licenses.csv" | grep -v "\.github/workflows/" || echo "")
            
            echo "Changed files:"
            echo "$CHANGED_FILES"
            
            if [ -z "${CHANGED_FILES}" ]; then
              echo "No relevant files in PR #${PR_NUM}. Skipping."
              continue
            fi
            
            # Create patch
            git diff ${BASE_SHA} ${HEAD_SHA} -- ${CHANGED_FILES} > pr-${PR_NUM}.patch
            
            # Process in target repo
            cd opentelemetry-ebpf-instrumentation
            
            # Create branch
            BRANCH_NAME="port/${PR_NUM}-to-upstream"
            echo "Creating/checking out branch ${BRANCH_NAME}"
            git checkout -b ${BRANCH_NAME} 2>/dev/null || git checkout ${BRANCH_NAME}
            git reset --hard origin/main
            
            # Apply patch with rejects
            echo "Applying patch..."
            git apply --whitespace=fix --reject ../pr-${PR_NUM}.patch || true
            
            # Remove workflow .rej files that would cause permission issues
            find . -path "./.github/workflows/*.rej" -delete
            
            # Commit and push changes
            if ! git diff --quiet || ! git diff --staged --quiet || [ -n "$(find . -name '*.rej')" ]; then
              echo "Changes detected, committing..."
              git add .
              git commit -m "[port] #${PR_NUM}: ${PR_TITLE}
              
              Automated port of #${PR_NUM} from grafana/beyla.
              Original PR: ${PR_URL}"
              
              # Try to push, but continue even if it fails
              echo "Pushing branch ${BRANCH_NAME}..."
              git push origin ${BRANCH_NAME} --force || {
                echo "Failed to push branch ${BRANCH_NAME} for PR #${PR_NUM}. Continuing with next PR."
              }
              echo "Branch ${BRANCH_NAME} pushed successfully"
            else
              echo "No changes to commit for PR #${PR_NUM}"
            fi
            
            # Go back to Beyla repository
            cd ..
          done
          
          echo "All PRs processed."
