name: Port to Upstream OTel eBPF Instrumentation

on:
  pull_request:
    types: [opened, synchronize, labeled, closed]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  port-to-upstream:
    if: |
      github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            GITHUB_APP_ID=github-app:app-id
            GITHUB_APP_INSTALLATION_ID=github-app:app-installation-id
            GITHUB_APP_PRIVATE_KEY=github-app:private-key
      - name: Checkout Beyla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.GITHUB_APP_ID }}
          private-key: ${{ env.GITHUB_APP_PRIVATE_KEY }}
          owner: grafana
          repositories: "opentelemetry-ebpf-instrumentation"
      - name: Push changes to fork for upstream PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH=port/${{ github.event.pull_request.number }}-to-upstream
          git checkout -b $BRANCH
          git remote add upstream-fork https://x-access-token:${GH_TOKEN}@github.com/grafana/opentelemetry-ebpf-instrumentation.git
          git push upstream-fork $BRANCH --force
      - name: Create PR to upstream repo
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr create \
            --title "[port] #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" \
            --body "Automated port of #${{ github.event.pull_request.number }} from grafana/beyla." \
            --repo open-telemetry/opentelemetry-ebpf-instrumentation \
            --head grafana:port/${{ github.event.pull_request.number }}-to-upstream \
            --base main \
            --draft
