name: Check third-party licenses

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]

# Set restrictive permissions at workflow level
permissions:
  contents: read

jobs:
  check-licenses:
    name: check-licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: "false"
          go-version-file: "go.mod"
      - name: Check licenses
        run: make check-licenses
