name: Check third-party licenses

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]

# Set restrictive permissions at workflow level
permissions:
  contents: read

jobs:
  check-licenses:
    name: check-licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          cache: "false"
          go-version-file: "go.mod"
      - name: Check licenses
        run: make check-licenses
