name: Check third-party licenses

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]

# Set restrictive permissions at workflow level
permissions:
  contents: read

jobs:
  check-licenses:
    name: check-licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          cache: "false"
          go-version-file: "go.mod"
      - name: Check licenses
        run: make check-licenses
