name: Release binaries
on:
  release:
    types:
      - published

jobs:
  release-binaries:
    name: Release compiled binaries for Linux/${{matrix.arch}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64','arm64']
        go: [ '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Build Go release for linux/${{ matrix.arch }}
        run: make artifact
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
      - name: Upload release asset
        uses: echapmanFromBunnings/upload-release-assets@1.3
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
          VERSION: ${{ github.event.release.tag_name }}
        with:
          releaseTag: ${{ github.event.release.tag_name }}
          gitHubToken: ${{ github.token }}
          # TODO: change name when we get a definitive name
          files: |
            otelauto-linux-${{ matrix.arch }}-${{ github.event.release.tag_name }}.tar.gz
