name: Security Check for External Contributions

# Make this action run before any other action
on:
  pull_request:
    types: [opened, synchronize, reopened]

# This ensures this workflow runs first
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-check:
    name: Check for sensitive file modifications
    runs-on: ubuntu-latest
    # Set a default to allow the workflow to complete even if we cancel others
    outputs:
      cancel_workflows: ${{ steps.check-files.outputs.cancel_workflows || 'false' }}
      modified_files: ${{ steps.check-files.outputs.modified_files }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to properly check file changes
      
    - name: Check if PR is from external contributor and sensitive files were modified
      id: check-files
      run: |
        # Check if the PR author is a collaborator/member
        if gh api repos/${{ github.repository }}/collaborators/${{ github.event.pull_request.user.login }} --silent 2>/dev/null; then
          echo "PR author is a collaborator, no need to cancel workflows"
          echo "cancel_workflows=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # If we get here, PR is from external contributor
        echo "PR is from an external contributor, checking modified files..."
        
        # Get the files changed in the PR
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        MODIFIED_FILES=""
        
        # Check for modifications to sensitive files
        if echo "$CHANGED_FILES" | grep -q -E '^\.github/'; then
          MODIFIED_FILES="${MODIFIED_FILES} .github/ directory,"
        fi
        if echo "$CHANGED_FILES" | grep -q -E '^tools/'; then
          MODIFIED_FILES="${MODIFIED_FILES} tools/ directory,"
        fi
        if echo "$CHANGED_FILES" | grep -q -E 'cmd/beyla-genfiles/beyla_genfiles\.go'; then
          MODIFIED_FILES="${MODIFIED_FILES} beyla_genfiles.go,"
        fi
        
        # Check for any modifications to Makefile
        if echo "$CHANGED_FILES" | grep -q -E '^Makefile$'; then
          MODIFIED_FILES="${MODIFIED_FILES} Makefile,"
        fi
        
        # Remove trailing comma if any
        MODIFIED_FILES=$(echo "$MODIFIED_FILES" | sed 's/,$//g')
        
        if [ -n "$MODIFIED_FILES" ]; then
          echo "Sensitive files were modified by an external contributor"
          echo "cancel_workflows=true" >> $GITHUB_OUTPUT
          echo "modified_files=$MODIFIED_FILES" >> $GITHUB_OUTPUT
        else
          echo "No sensitive files were modified"
          echo "cancel_workflows=false" >> $GITHUB_OUTPUT
          echo "modified_files=" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Warn about canceled workflows
      if: steps.check-files.outputs.cancel_workflows == 'true'
      run: |
        echo "::warning::External contribution modifies sensitive files. Subsequent workflows will be canceled for security review."

    - name: Comment on PR about security concerns
      if: steps.check-files.outputs.cancel_workflows == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const modifiedFiles = '${{ steps.check-files.outputs.modified_files }}';
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `## ⚠️ Security Review Required ⚠️
            
            Thank you for your contribution! 
            
            This PR requires a security review because it modifies sensitive files:
            - ${modifiedFiles}
            
            These files can affect the project's build system, CI/CD workflows, or other security-sensitive areas. All other automated checks have been temporarily paused until a maintainer reviews these changes.
            
            **Note to maintainers:** Please review these changes carefully before allowing other workflows to proceed.`
          });
        
  cancel-workflows:
    name: Cancel subsequent workflows if needed
    needs: security-check
    if: needs.security-check.outputs.cancel_workflows == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Cancel subsequent workflows
      uses: andymckay/cancel-action@0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        workflow_id: pull_request.yml,pull_request_k8s_integration_tests.yml,pull_request_oats_test.yml,pull_request_integration_tests.yml,pull_request_integration_tests_arm.yml,pull_request_integration_tests_vm_5.15_x86_64.yml,pull_request_check_license.yml,clang-format-check.yml,helm-test.yml,generator-image.yml,backport.yml,vale.yml,workflow_integration_tests_vm.yml