name: Security Check for External Contributions

# Make this action run only when a PR is initially opened
on:
  pull_request:
    types: [opened]

# This ensures this workflow runs first
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-check:
    name: Check for external contributions with sensitive file modifications
    runs-on: ubuntu-latest
    # Set a default to allow the workflow to complete even if we cancel others
    outputs:
      cancel_workflows: ${{ steps.check-files.outputs.cancel_workflows || 'false' }}
      modified_files: ${{ steps.check-files.outputs.modified_files }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to properly check file changes
      
    - name: Check if PR is from external contributor and sensitive files were modified
      id: check-files
      shell: bash
      env:
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        REPO: ${{ github.repository }}
        REPO_OWNER: ${{ github.repository_owner }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if PR author is from the same organization
        ORG_MEMBER=false

        # Check if PR author is a collaborator
        IS_COLLABORATOR=false
        if gh api "repos/${REPO}/collaborators/${PR_AUTHOR}" --silent 2>/dev/null; then
          echo "PR author is a collaborator"
          IS_COLLABORATOR=true
        fi

        # If we have an organization, check if the user is a member
        if [[ "${REPO_OWNER}" != *"/"* ]]; then
          if gh api "orgs/${REPO_OWNER}/members/${PR_AUTHOR}" --silent 2>/dev/null; then
            echo "PR author is an organization member"
            ORG_MEMBER=true
          fi
        fi

        # If PR author is either a collaborator or an org member, no need for security review
        if [[ "$IS_COLLABORATOR" == "true" || "$ORG_MEMBER" == "true" ]]; then
          echo "PR author is a trusted contributor, no need for security review"
          echo "cancel_workflows=false" >> $GITHUB_OUTPUT
          echo "modified_files=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # If we get here, PR is from external contributor
        echo "PR is from an external contributor, checking modified files..."
        
        # Get the files changed in the PR
        CHANGED_FILES=$(git diff --name-only "${BASE_SHA}" "${HEAD_SHA}")
        MODIFIED_FILES=""
        
        # Check for modifications to sensitive files
        if echo "$CHANGED_FILES" | grep -q -E '^\.github/'; then
          MODIFIED_FILES="${MODIFIED_FILES} .github/ directory,"
        fi
        if echo "$CHANGED_FILES" | grep -q -E '^tools/'; then
          MODIFIED_FILES="${MODIFIED_FILES} tools/ directory,"
        fi
        if echo "$CHANGED_FILES" | grep -q -E 'cmd/beyla-genfiles/beyla_genfiles\.go'; then
          MODIFIED_FILES="${MODIFIED_FILES} beyla_genfiles.go,"
        fi
        
        # Check for any modifications to Makefile
        if echo "$CHANGED_FILES" | grep -q -E '^Makefile$'; then
          MODIFIED_FILES="${MODIFIED_FILES} Makefile,"
        fi
        
        # Remove trailing comma if any
        MODIFIED_FILES=$(echo "$MODIFIED_FILES" | sed 's/,$//g')
        
        if [ -n "$MODIFIED_FILES" ]; then
          echo "Sensitive files were modified by an external contributor"
          echo "cancel_workflows=true" >> $GITHUB_OUTPUT
          echo "modified_files=$MODIFIED_FILES" >> $GITHUB_OUTPUT
        else
          echo "No sensitive files were modified by external contributor"
          echo "cancel_workflows=false" >> $GITHUB_OUTPUT
          echo "modified_files=" >> $GITHUB_OUTPUT
        fi
        
    - name: Warn about canceled workflows
      if: steps.check-files.outputs.cancel_workflows == 'true'
      run: |
        echo "::warning::External contribution modifies sensitive files. Subsequent workflows will be canceled for security review."

    - name: Comment on PR about security concerns
      if: steps.check-files.outputs.cancel_workflows == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const modifiedFiles = '${{ steps.check-files.outputs.modified_files }}';
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `## ⚠️ Security Review Required for External Contribution ⚠️
            
            Thank you for your contribution! 
            
            As you're not a repository collaborator, this PR requires a security review because it modifies sensitive files:
            - ${modifiedFiles}
            
            These files can affect the project's build system, CI/CD workflows, or other security-sensitive areas. All other automated checks have been temporarily paused until a maintainer reviews these changes.
            
            **Note to maintainers:** Please review these changes carefully before allowing other workflows to proceed.`
          });
        
  cancel-workflows:
    name: Cancel subsequent workflows if needed
    needs: security-check
    if: needs.security-check.outputs.cancel_workflows == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Cancel subsequent workflows
      uses: styfle/cancel-workflow-action@85f0a91c15966e96a22b7c370a08e43cd66567a8 # 0.12.0
      with:
        # Cancel all workflows running on this PR, not just the specific ones listed
        access_token: ${{ github.token }}
        pull_request: ${{ github.event.pull_request.number }}
        workflow_id: "*"