name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale@sha256:6e38e76afd31739c060ce18182b13c6376c3d2d9aaf06d0f98757d501cae3007
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/vale-action@f49dd90f007967990095ac2d18c5bdf37b412a5f # vale-action/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
