name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale@sha256:eb78672ef59d80bd7d6c7f9a9377cfaf1b6de47c4082adbe9b1f7204b983198f
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/vale-action@67d43d461804a3413c2e11fd7899ff01e05b2563 # vale-action/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
