# Dockerfile that will build a container that runs python flask with gunicorn on port 7770
FROM python:3.14.2-slim@sha256:3955a7dd66ccf92b68d0232f7f86d892eaf75255511dc7e98961bdc990dc6c9b
EXPOSE 7773
RUN pip install flask gunicorn requests
# Alternative: RUN pip install flask uwsgi

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY internal/test/integration/components/pythonserver .

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:7773", "main_7773:app"]
# CMD uwsgi --http 0.0.0.0:7770 --master -p 4 -w main:app
